import { clamp01, hexToRgba, normalizeTypeName } from "./helpers";
import { uniformParamExpression, uniformVec4Expression } from "./uniforms";

type ArrayParamType = {
  elementType: string;
  length: number;
};

type UniformValueExpression = {
  expression: string;
  slotWidth: number;
};

export function canonicalizeParamType(type: unknown): string {
  const raw = normalizeTypeName(type);
  if (!raw) {
    return "";
  }

  if (raw === "color") {
    return "color";
  }

  const vecMatch = /^vec([234])(?:<f32>|f)?$/i.exec(raw);
  if (vecMatch) {
    return `vec${vecMatch[1]}<f32>`;
  }

  const matMatch = /^mat([234])(?:x([234]))?(?:<f32>|f)?$/i.exec(raw);
  if (matMatch) {
    const cols = matMatch[1];
    const rows = matMatch[2] || matMatch[1];
    return `mat${cols}x${rows}<f32>`;
  }

  return raw;
}

export function parseArrayParamType(type: unknown): ArrayParamType | null {
  const raw = normalizeTypeName(type);
  const match = /^array<\s*(.+?)\s*,\s*(\d+)(?:u)?\s*>$/i.exec(raw);
  if (!match) {
    return null;
  }
  return {
    elementType: canonicalizeParamType(match[1]),
    length: Number.parseInt(match[2], 10) || 0
  };
}

type DynamicArrayParamType = {
  elementType: string;
};

/**
 * Parses a dynamic (runtime-sized) array type like `array<f32>` or `array<vec4<f32>>`.
 * Returns null for fixed-size arrays (e.g. `array<f32, 3>`) or non-array types.
 * Dynamic arrays are backed by storage buffers, not uniform slots.
 */
export function parseDynamicArrayParamType(type: unknown): DynamicArrayParamType | null {
  const raw = normalizeTypeName(type);
  // Fixed-size arrays like array<f32, 3> are handled by parseArrayParamType; not dynamic.
  if (parseArrayParamType(raw) !== null) {
    return null;
  }
  // Must start with "array<" (case-insensitive) and end with ">".
  if (!/^array</i.test(raw) || !raw.endsWith(">")) {
    return null;
  }
  // Find the matching closing ">" of the outermost array<...>, tracking angle-bracket depth.
  let depth = 0;
  let closeIndex = -1;
  for (let i = 6; i < raw.length; i++) { // i=6 is the first char after "array<"
    const ch = raw[i];
    if (ch === "<") {
      depth += 1;
    } else if (ch === ">") {
      if (depth === 0) {
        closeIndex = i;
        break;
      }
      depth -= 1;
    }
  }
  if (closeIndex !== raw.length - 1) {
    return null;
  }
  const elementType = raw.slice(6, closeIndex).trim();
  if (!elementType) {
    return null;
  }
  return { elementType: canonicalizeParamType(elementType) };
}

export function scalarSlotWidthForType(type: unknown): number {
  const t = canonicalizeParamType(type);
  if (!t) {
    return 0;
  }
  if (t === "f32" || t === "i32" || t === "u32" || t === "bool") {
    return 1;
  }
  if (t === "color") {
    return 4;
  }
  const vecMatch = /^vec([234])<f32>$/.exec(t);
  if (vecMatch) {
    return Number.parseInt(vecMatch[1], 10) || 0;
  }
  const matMatch = /^mat([234])x([234])<f32>$/.exec(t);
  if (matMatch) {
    const cols = Number.parseInt(matMatch[1], 10) || 0;
    const rows = Number.parseInt(matMatch[2], 10) || 0;
    return cols * rows;
  }
  return 0;
}

export function totalSlotWidthForType(type: unknown): number {
  const arrayInfo = parseArrayParamType(type);
  if (arrayInfo) {
    return arrayInfo.length * scalarSlotWidthForType(arrayInfo.elementType);
  }
  return scalarSlotWidthForType(type);
}

/**
 * Returns the byte size to allocate for a dynamic-array storage buffer.
 *
 * WGSL's arrayLength() derives the element count from the bound buffer size:
 *   arrayLength = floor(bufferBytes / stride)
 *
 * WebGPU requires a minimum of 4 bytes, but that only guarantees
 * arrayLength >= 1 when stride == 4.  For wider element types (vec4, mat4x4,
 * etc.) a 4-byte buffer would yield arrayLength = 0.
 *
 * To keep the invariant "arrayLength returns 1 for an empty array" regardless
 * of element type, the minimum is always one full element stride.  Shaders
 * generated by fresco already guard array accesses with `i < arrayLength(&arr)`
 * so the phantom zero-initialised element is never read.
 */
export function storageBufferByteSize(elementType: unknown, items: unknown[]): number {
  const componentWidth = scalarSlotWidthForType(elementType) || 1;
  const elementCount = Math.floor(items.length / componentWidth);
  const strideBytes = componentWidth * 4;
  return Math.max(strideBytes, elementCount * strideBytes);
}

export function wgslTypeForParamType(type: unknown): string {
  const arrayInfo = parseArrayParamType(type);
  if (arrayInfo) {
    return `array<${wgslTypeForParamType(arrayInfo.elementType)}, ${arrayInfo.length}>`;
  }

  const t = canonicalizeParamType(type);
  if (!t) {
    return "f32";
  }
  if (t === "color") {
    return "vec4<f32>";
  }
  if (t === "bool" || t === "f32" || t === "i32" || t === "u32") {
    return t;
  }

  const vecMatch = /^vec([234])<f32>$/.exec(t);
  if (vecMatch) {
    return `vec${vecMatch[1]}<f32>`;
  }

  const matMatch = /^mat([234])x([234])<f32>$/.exec(t);
  if (matMatch) {
    return `mat${matMatch[1]}x${matMatch[2]}<f32>`;
  }

  return t;
}

export function buildUniformValueExpression(type: unknown, index: number): UniformValueExpression {
  const arrayInfo = parseArrayParamType(type);
  if (arrayInfo) {
    const elementWidth = scalarSlotWidthForType(arrayInfo.elementType);
    const parts: string[] = [];
    let cursor = index;
    for (let i = 0; i < arrayInfo.length; i += 1) {
      const next = buildUniformValueExpression(arrayInfo.elementType, cursor);
      parts.push(next.expression);
      cursor += next.slotWidth;
    }
    return {
      expression: `array<${wgslTypeForParamType(arrayInfo.elementType)}, ${arrayInfo.length}>(${parts.join(", ")})`,
      slotWidth: arrayInfo.length * elementWidth
    };
  }

  const t = canonicalizeParamType(type);
  if (t === "bool") {
    return {
      expression: `(${uniformParamExpression(index)} >= 0.5)`,
      slotWidth: 1
    };
  }
  if (t === "u32") {
    return {
      expression: `u32(max(${uniformParamExpression(index)}, 0.0))`,
      slotWidth: 1
    };
  }
  if (t === "i32") {
    return {
      expression: `i32(round(${uniformParamExpression(index)}))`,
      slotWidth: 1
    };
  }
  if (t === "color") {
    return {
      expression: uniformVec4Expression(index),
      slotWidth: 4
    };
  }

  const vecMatch = /^vec([234])<f32>$/.exec(t);
  if (vecMatch) {
    const width = Number.parseInt(vecMatch[1], 10) || 0;
    const components: string[] = [];
    for (let i = 0; i < width; i += 1) {
      components.push(uniformParamExpression(index + i));
    }
    return {
      expression: `vec${width}<f32>(${components.join(", ")})`,
      slotWidth: width
    };
  }

  const matMatch = /^mat([234])x([234])<f32>$/.exec(t);
  if (matMatch) {
    const cols = Number.parseInt(matMatch[1], 10) || 0;
    const rows = Number.parseInt(matMatch[2], 10) || 0;
    const components: string[] = [];
    for (let i = 0; i < cols * rows; i += 1) {
      components.push(uniformParamExpression(index + i));
    }
    return {
      expression: `mat${cols}x${rows}<f32>(${components.join(", ")})`,
      slotWidth: cols * rows
    };
  }

  return {
    expression: uniformParamExpression(index),
    slotWidth: 1
  };
}

export function normalizeScalarValueByType(type: unknown, value: unknown, fallback: unknown = undefined): number | boolean {
  const t = canonicalizeParamType(type);
  const fallbackValue = fallback;
  if (t === "bool") {
    if (typeof value === "boolean") {
      return value;
    }
    if (typeof value === "number") {
      return value !== 0;
    }
    if (typeof value === "string") {
      const lowered = value.trim().toLowerCase();
      if (lowered === "true") {
        return true;
      }
      if (lowered === "false") {
        return false;
      }
      const numeric = Number(lowered);
      if (Number.isFinite(numeric)) {
        return numeric !== 0;
      }
    }
    return fallbackValue !== undefined ? Boolean(fallbackValue) : false;
  }

  const numeric = Number(value);
  const fallbackNum = Number(fallbackValue);
  const source = Number.isFinite(numeric)
    ? numeric
    : (Number.isFinite(fallbackNum) ? fallbackNum : 0);

  if (t === "u32") {
    return Math.max(0, Math.round(source));
  }
  if (t === "i32") {
    return Math.round(source);
  }
  return source;
}

export function flattenParamComponents(type: unknown, value: unknown, fallback: unknown = undefined): number[] | null {
  const t = canonicalizeParamType(type);
  const width = scalarSlotWidthForType(t);
  if (width <= 0) {
    return null;
  }

  if (width === 1) {
    return [Number(normalizeScalarValueByType(t, value, fallback))];
  }

  const fallbackSlots: unknown[] = [];
  if (Array.isArray(fallback)) {
    for (const item of fallback) {
      fallbackSlots.push(item);
    }
  }

  if (t === "color" && typeof value === "string") {
    const alpha = Number(fallbackSlots[3]);
    const rgba = hexToRgba(value, Number.isFinite(alpha) ? alpha : 1);
    return rgba.slice(0, width).map((channel) => clamp01(channel));
  }

  const sourceSlots: unknown[] = [];
  const pushFlattened = (candidate: unknown) => {
    if (Array.isArray(candidate)) {
      for (const item of candidate) {
        pushFlattened(item);
      }
      return;
    }
    sourceSlots.push(candidate);
  };
  pushFlattened(value);

  const out: number[] = [];
  for (let i = 0; i < width; i += 1) {
    const raw = i < sourceSlots.length ? sourceSlots[i] : fallbackSlots[i];
    let normalized = Number(
      normalizeScalarValueByType("f32", raw, i < fallbackSlots.length ? fallbackSlots[i] : 0)
    );
    if (t === "color") {
      normalized = clamp01(Number(normalized) || 0);
    }
    out.push(normalized);
  }
  return out;
}

export function paramValueEquals(left: unknown, right: unknown): boolean {
  if (Array.isArray(left) || Array.isArray(right)) {
    if (!Array.isArray(left) || !Array.isArray(right)) {
      return false;
    }
    if (left.length !== right.length) {
      return false;
    }
    for (let i = 0; i < left.length; i += 1) {
      if (left[i] !== right[i]) {
        return false;
      }
    }
    return true;
  }
  return left === right;
}
